Repository wix/react-native-navigation, pull requests merged in 2018-05, with the labels that each got.

#3109 IOS: Fix custom top bar from disappearing after a push
  lib/ios/RNNRootViewController.m
Labels: v2

#1578 Support a “modal” prop for tabbed iOS apps
  docs/top-level-api.md
  ios/RCCTabBarController.m
Labels: v1

#3153 Implemented test for public constructor
  lib/android/app/src/test/java/com/reactnativenavigation/react/ReactGatewayTest.java
Labels: v2

#3152 Implement images loader
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoader.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ImageLoadingListenerAdapter.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/NoOpPromise.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TopBarButtonController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/Fab.java
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/ImageLoaderMock.java
Labels: v2

#3168 Fix top bar title positioning.
  lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
Labels: v2

#3215 Modal unmount e2e test
  e2e/Modals.test.js
  playground/src/screens/LifecycleScreen.js
  playground/src/screens/ModalScreen.js
  playground/src/testIDs.js
Labels: v2

#3150 A few improvements for Android
  lib/android/app/src/main/java/com/reactnativenavigation/parse/LayoutFactory.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsOptionsPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/SideMenuOptionsPresenter.java
Labels: v2

#3247 [v2] UISplitViewController
  docs/docs/layout-types.md
  lib/ios/RNNCommandsHandler.m
  lib/ios/RNNControllerFactory.m
  lib/ios/RNNLayoutNode.h
  lib/ios/RNNLayoutNode.m
  lib/ios/RNNNavigationOptions.m
  lib/ios/RNNRootViewProtocol.h
  lib/ios/RNNSplitViewController.h
  lib/ios/RNNSplitViewController.m
  lib/ios/RNNSplitViewOptions.h
  lib/ios/RNNSplitViewOptions.m
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
  lib/src/commands/LayoutTreeParser.test.ts
  lib/src/commands/LayoutTreeParser.ts
  lib/src/commands/LayoutType.ts
  playground/ios/playground.xcodeproj/project.pbxproj
  playground/src/screens/WelcomeScreen.js
  playground/src/testIDs.js
  yarn.lock
Labels: iOS, v2
