Repository wix/react-native-navigation, pull requests merged in 2018-07, with the labels that each got.

#3339 Expose public method to find VC
  lib/ios/RNNBridgeManager.h
  lib/ios/RNNBridgeManager.m
  lib/ios/ReactNativeNavigation.h
  lib/ios/ReactNativeNavigation.m
  lib/src/Navigation.ts
  lib/src/adapters/Element.tsx
Labels: platform: iOS, v2

#3459 Support storyboards in the splash screen & fix white red box on iOS
  lib/ios/RNNSplashScreen.m
Labels: platform: iOS, v2

#3487 Unmount react views when bundle load completes
  lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/BundleDownloadListenerProvider.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
  lib/android/app/src/test/java/com/reactnativenavigation/react/ReloadListenerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/NavigatorTest.java
  playground/src/screens/PushedScreen.js
Labels: v2

#3425 Fix docs syntax on declaring buttons statically
  docs/docs/topBar-buttons.md
Labels: v2

#3497 [BREAKING] Event registry rework
  docs/api/Commands.md
  docs/api/ComponentEventsObserver.md
  docs/api/ComponentRegistry.md
  docs/api/Constants.md
  docs/api/Element.md
  docs/api/EventsRegistry.md
  docs/api/LayoutTreeParser.md
  docs/api/LayoutType.md
  docs/api/NativeCommandsSender.md
  docs/api/NativeEventsReceiver.md
  docs/api/Navigation.md
  docs/api/README.md
  docs/api/Store.md
  docs/api/_sidebar.md
  docs/docs/events.md
  lib/android/app/src/main/java/com/reactnativenavigation/react/EventEmitter.java
  lib/ios/RNNCommandsHandler.m
  lib/ios/RNNEventEmitter.h
  lib/ios/RNNEventEmitter.m
  lib/ios/RNNRootViewController.m
  lib/ios/RNNTabBarController.m
  lib/src/Navigation.ts
  lib/src/adapters/NativeEventsReceiver.ts
  lib/src/components/ComponentRegistry.test.tsx
  lib/src/components/ComponentRegistry.ts
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/components/Store.test.ts
  lib/src/components/Store.ts
  lib/src/events/CommandsObserver.ts
  lib/src/events/ComponentEventsObserver.test.ts
  lib/src/events/ComponentEventsObserver.test.tsx
  lib/src/events/ComponentEventsObserver.ts
  lib/src/events/EventsRegistry.test.ts
  lib/src/events/EventsRegistry.test.tsx
  lib/src/events/EventsRegistry.ts
  lib/src/interfaces/ComponentEvents.ts
  lib/src/interfaces/Events.ts
  playground/src/screens/CustomRoundedButton.js
  playground/src/screens/CustomTopBar.js
  playground/src/screens/LifecycleScreen.js
  playground/src/screens/OptionsScreen.js
  playground/src/screens/PushedScreen.js
  playground/src/screens/SearchScreen.js
  playground/src/screens/StaticLifecycleOverlay.js
  playground/src/screens/TopBarBackground.js
  scripts/gen-docs/ClassParser.ts
Labels: v2

#3441 Revert "Fix/rootview bounds iphone x"
  ios/RCCViewController.m
Labels: v1

#3548 Fix app crash bug when reload [cmd + r]
  ios/RCCViewController.m
Labels: v1

#3501 Fix #3450: TopBar got missed when SearchBar is focused
  lib/ios/RNNTopBarOptions.m
  playground/src/screens/SearchScreen.js
Labels: platform: iOS, v2

#3519 [v2] Support UIBarStyle for topBar and bottomTabs
  docs/docs/styling.md
  lib/ios/RNNBottomTabsOptions.h
  lib/ios/RNNBottomTabsOptions.m
  lib/ios/RNNTopBarOptions.h
  lib/ios/RNNTopBarOptions.m
Labels: type: accepted/enhancement, v2

#3604 [v2] Add badgeColor option to bottomTab
  docs/docs/styling.md
  lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabOptionsPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
  lib/ios/RNNBottomTabOptions.h
  lib/ios/RNNBottomTabOptions.m
Labels: type: accepted/enhancement, v2

#3611 [v2][iOS] Simplify searchBarHiddenWhenScrolling making its behaviour default to iOS one
  lib/ios/RNNRootViewController.m
  lib/ios/RNNTopBarOptions.m
Labels: platform: iOS, v2
