Repository wix/react-native-navigation, pull requests merged in 2018-02, with the labels that each got.

#2700 BottomTab badge is applied
  lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabOptionsPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ParentController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabsControllerTest.java
Labels: v2

#2673 WIP - Detox e2e for android
  e2e/CustomTransition.js
  e2e/Orientations.test.js
  e2e/ScreenStack.test.js
  e2e/ScreenStyle.test.js
  e2e/TopLevelApi.test.js
  lib/android/app/src/main/java/com/reactnativenavigation/parse/TopBarOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/OptionsPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/TopBar.java
  package.json
  playground/android/app/build.gradle
  playground/android/app/src/androidTest/java/com/reactnativenavigation/playground/DetoxTest.java
  playground/android/settings.gradle
  playground/src/screens/LifecycleScreen.js
  playground/src/screens/OptionsScreen.js
  playground/src/screens/OrientationDetectScreen.js
  playground/src/screens/OrientationSelectScreen.js
  playground/src/screens/TextScreen.js
  playground/src/testIDs.js
  scripts/test.e2e.android.detox.js
Labels: Android, v2

#2750 rename disabled to enabled
  lib/android/app/src/main/java/com/reactnativenavigation/parse/Button.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/TitleBarButton.java
Labels: v2

#2755 Invoke onNavigationButtonPressed on button press
  lib/android/app/src/main/java/com/reactnativenavigation/parse/Button.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/Navigator.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/SideMenuController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/StackLayout.java
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/BottomTabsControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ComponentViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ParentControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopTabsViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/views/TopBarTest.java
Labels: v2

#2754 Added ability to specify font size for tab bar labels on Android
  android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java
  android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java
  android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
  android/gradle/wrapper/gradle-wrapper.properties
  docs/styling-the-tab-bar.md
  src/deprecated/platformSpecificDeprecated.android.js
Labels: v1

#2770 deep stack for startTabBasedApp and startSingleScreenApp
  ios/RCCNavigationController.m
  src/deprecated/platformSpecificDeprecated.ios.js
Labels: iOS, v1
