Repository wix/react-native-navigation, pull requests merged in 2020-07, with the labels that each got.

#6331 Emit componentDidAppear after appear animation completes
  lib/android/app/src/main/java/com/reactnativenavigation/anim/StackAnimator.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/OverlayManager.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/RootPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/CollectionUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ParentController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarReactViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/externalcomponent/ExternalComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/ModalStack.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerBuilder.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/topbar/TopBarBackgroundViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsAdapter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/toptabs/TopTabsController.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ComponentViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ExternalComponentViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/FloatingActionButtonTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ParentControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopBarButtonControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopTabsViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attachmode/AfterInitialTabTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllersRegistryTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/fakes/FakeParentController.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/modal/ModalStackTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/RootPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/overlay/OverlayManagerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
Labels: platform: Android, type: accepted/bug

#6352 Combine start-windows and start command
  package.json
  scripts/start-windows.js
  scripts/start.js
Labels: Infrastructure

#6350 Fix TypeScript errors in the Playground app
  lib/src/adapters/TouchablePreview.tsx
  lib/src/interfaces/Layout.ts
  lib/src/interfaces/Options.ts
  package.json
  playground/src/commons/Options.ts
  playground/src/context/index.tsx
  playground/src/declarations.d.ts
  playground/src/screens/Alert.tsx
  playground/src/screens/Button.tsx
  playground/src/screens/ContextScreen.tsx
  playground/src/screens/NavigationScreen.tsx
  playground/src/screens/OptionsScreen.tsx
  playground/src/screens/OrientationDetectScreen.tsx
  playground/src/screens/OverlayAlert.tsx
  playground/src/screens/ScrollViewScreen.tsx
  playground/src/screens/SecondBottomTabScreen.tsx
  playground/src/screens/SideMenuLeftScreen.tsx
  playground/src/screens/StackScreen.tsx
  playground/src/screens/StaticLifecycleOverlay.tsx
  playground/src/screens/Toast.tsx
  playground/src/screens/TopTabOptionsScreen.tsx
  playground/src/screens/TopTabScreen.tsx
  playground/src/screens/complexlayouts/BottomTabSideMenuScreen.tsx
  playground/src/screens/sharedElementTransition/CocktailDetailsScreen.tsx
  playground/src/screens/sharedElementTransition/CocktailsView.tsx
Labels: Infrastructure

#6349 Enable experimental LogBox in Playground
  playground/src/app.ts
Labels: Infrastructure

#6354 Support lazy screen registration
  e2e/LazyRegsitration.test.js
  lib/src/Navigation.ts
  lib/src/components/Store.test.ts
  lib/src/components/Store.ts
  playground/src/screens/LazilyRegisteredScreen.tsx
  playground/src/screens/Screens.ts
  playground/src/screens/StackScreen.tsx
  playground/src/screens/index.tsx
  playground/src/testIDs.ts
Labels: Infrastructure, Wix

#6355 Add docs for setLazyComponentRegistrator
  website/api/api-component.mdx
Labels: Wix, type: documentation

#6356 Lazy load components from options
  e2e/LazyRegsitration.test.js
  lib/src/commands/OptionsProcessor.test.ts
  lib/src/commands/OptionsProcessor.ts
  lib/src/components/Store.ts
  playground/src/screens/LazilyRegisteredScreen.tsx
  playground/src/screens/LazyTopBar.tsx
  playground/src/screens/Screens.ts
  playground/src/screens/index.tsx
  playground/src/testIDs.ts
Labels: Infrastructure

#6351 Remove all remaining code related to the old documentation
  package.json
  scripts/gen-docs/ClassParser.ts
  scripts/gen-docs/EnumParser.ts
  scripts/gen-docs/Main.ts
  scripts/gen-docs/MarkdownWriter.ts
  scripts/gen-docs/ReflectionsReader.ts
  scripts/gen-docs/templates/class.hbs
  scripts/gen-docs/templates/enum.hbs
  scripts/gen-docs/templates/menu.hbs
  scripts/gen-docs/templates/method.hbs
  scripts/gen-docs/templates/property.hbs
  scripts/local-docs.js
Labels: Infrastructure, type: documentation

#6362 Update style-constants.mdx
  website/docs/style-constants.mdx
Labels: type: documentation

#6363 ✏️ Fixed typo error
  website/api/api-component.mdx
Labels: type: documentation

#6364 Fixed type
  website/api/api-stack.mdx
Labels: type: documentation

#6357 Fix back button testID
  e2e/Buttons.test.js
  lib/ios/RNNStackPresenter.m
  lib/ios/TopBarPresenter.m
  lib/ios/UINavigationController+RNNOptions.h
  lib/ios/UINavigationController+RNNOptions.m
  lib/ios/Utils/UIView+Utils.h
  lib/ios/Utils/UIView+Utils.m
  playground/ios/NavigationTests/RNNStackControllerTest.m
  playground/ios/NavigationTests/TopBarAppearancePresenterTest.m
  playground/ios/NavigationTests/utils/RNNComponentViewController+Utils.m
  playground/src/screens/PushedScreen.tsx
  playground/src/testIDs.ts
  website/api/options-backButton.mdx
Labels: platform: iOS, type: accepted/bug

#6365 Changed YES to yes to have consistent documentation format
  website/api/layout-layout.mdx
Labels: type: documentation

#6342 Document layout.direction locale option
  lib/src/interfaces/Options.ts
  website/api/options-layout.mdx
Labels: type: documentation

#6368 Added missing options in documentation
  website/api/options-backButton.mdx
  website/api/options-bottomTab.mdx
  website/api/options-fab.mdx
  website/api/options-statusBar.mdx
Labels: type: documentation

#6372 Fix overlay touch detection
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/reactnativenavigation/utils/MotionEvent.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/touch/OverlayTouchDelegate.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/touch/OverlayTouchDelegate.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/MotionEventTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/views/OverlayTouchDelegateTest.java
  playground/android/build.gradle
  playground/src/screens/Toast.tsx
Labels: platform: Android, type: accepted/bug

#6374 Avoid asserting bridge ready on setDefaultOptions
  lib/ios/RNNCommandsHandler.m
  playground/android/build.gradle
  playground/ios/NavigationTests/RNNCommandsHandlerTest.m
Labels: platform: iOS, type: accepted/bug

#6377 Bump detox to 17.1.1
  package.json
Labels: Infrastructure

#6378 Fixed up the doc and type for Fab button
  lib/src/interfaces/Options.ts
  website/api/options-fab.mdx
Labels: type: documentation

#6387 Fix changing disabled button color
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonSpan.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java
Labels: platform: Android, type: accepted/bug

#6393 Type component options
  lib/src/interfaces/NavigationComponent.ts
  lib/src/interfaces/NavigationFunctionComponent.ts
  lib/src/interfaces/Options.ts
  playground/src/commons/Layouts.ts
  playground/src/screens/FullScreenModalScreen.tsx
  playground/src/screens/LayoutsScreen.tsx
  playground/src/screens/ModalScreen.tsx
  playground/src/screens/PushedScreen.tsx
  playground/src/screens/SideMenuCenterScreen.tsx
  playground/src/screens/SideMenuLeftScreen.tsx
  playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx
  playground/src/screens/splitView/CocktailsListMasterScreen.tsx
  playground/src/services/Navigation.ts
  website/docs/third-party-typescript.mdx
  website/sidebars.js
Labels: type: accepted/enhancement

#6385 Support animating shared elements on pop
  lib/android/app/src/main/java/com/reactnativenavigation/options/AnimationOptions.kt
  lib/android/app/src/main/java/com/reactnativenavigation/options/ElementTransitions.kt
  lib/android/app/src/main/java/com/reactnativenavigation/options/SharedElements.java
  lib/android/app/src/main/java/com/reactnativenavigation/options/SharedElements.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackAnimator.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerBuilder.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/RootPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerOverlay.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/ElementTransitionManager.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/SharedElementTransition.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/TransitionAnimatorCreator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/TransitionSetCreator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ClipBoundsEvaluator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/MatrixAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ScaleXAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ScaleYAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/TextChangeAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/XAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/YAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/finder/ExistingViewFinder.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/finder/OptimisticViewFinder.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/element/finder/ViewFinder.kt
  lib/android/app/src/main/res/values/ids.xml
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/RootPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
  playground/src/screens/sharedElementTransition/CocktailDetailsScreen.tsx
  playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx
  playground/src/screens/sharedElementTransition/CocktailsView.tsx
  website/docs/style-animations.mdx
Labels: feature: Shared Element Transition, platform: Android, type: accepted/enhancement

#6394 Add Option processors
  lib/src/Navigation.ts
  lib/src/commands/Commands.ts
  lib/src/commands/LayoutTreeCrawler.test.ts
  lib/src/commands/LayoutTreeCrawler.ts
  lib/src/commands/OptionsProcessor.test.ts
  lib/src/commands/OptionsProcessor.ts
  lib/src/interfaces/ProcessorSubscription.ts
  lib/src/processors/OptionProcessorsStore.test.ts
  lib/src/processors/OptionProcessorsStore.ts
  wallaby.js
Labels: type: accepted/enhancement

#5086 [iOS] Support Fabric
  ReactNativeNavigation.podspec
  lib/ios/EnumParser.h
  lib/ios/EnumParser.m
  lib/ios/RNNBridgeManager.mm
  lib/ios/RNNReactView.h
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
Labels: platform: iOS, type: accepted/enhancement

#6400 Fix flickering BottomTabs when pushing a screen with waitForRender
  lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabs.java
  lib/android/app/src/test/java/com/reactnativenavigation/views/bottomtabs/BottomTabsTest.kt
Labels: platform: Android, type: accepted/bug

#6397 Add allCaps option to TopBar buttons
  lib/android/app/src/main/java/com/reactnativenavigation/options/ButtonOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
  lib/src/interfaces/Options.ts
Labels: platform: Android, type: accepted/enhancement

#6401 Document button.allCaps
  website/api/options-button.mdx
Labels: type: documentation

#6402 Add a dismiss button to all modals using Options Processors
  playground/img/x.android.png
  playground/img/x.png
  playground/img/x@1.5x.png
  playground/img/x@2x.android.png
  playground/img/x@2x.png
  playground/img/x@3x.android.png
  playground/img/x@3x.png
  playground/img/x@4x.png
  playground/src/app.ts
  playground/src/commons/OptionProcessors.ts
Labels: Infrastructure

#6407 Add layout processors
  lib/src/Navigation.ts
  lib/src/commands/Commands.test.ts
  lib/src/commands/Commands.ts
  lib/src/commands/OptionsProcessor.ts
  lib/src/index.ts
  lib/src/interfaces/CommandName.ts
  lib/src/interfaces/Processors.ts
  lib/src/processors/LayoutProcessor.test.ts
  lib/src/processors/LayoutProcessor.ts
  lib/src/processors/LayoutProcessorsStore.test.ts
  lib/src/processors/LayoutProcessorsStore.ts
  lib/src/processors/OptionProcessorsStore.ts
Labels: type: accepted/enhancement

#6409 Show deprecation warning while toggling bottomTabs visibility on iOS
  lib/src/commands/Deprecations.ts
  lib/src/commands/OptionsProcessor.test.ts
  lib/src/commands/OptionsProcessor.ts
Labels: Infrastructure

#6399 Turbo Modules support
  lib/ios/RNNBridgeManager.h
  lib/ios/RNNBridgeManager.mm
  lib/ios/ReactNativeNavigation.h
  lib/ios/ReactNativeNavigation.m
  lib/src/interfaces/Options.ts
  package.json
  playground/ios/Podfile
  playground/ios/playground.xcodeproj/project.pbxproj
  playground/ios/playground/AppDelegate.h
  playground/ios/playground/AppDelegate.m
  website/api/options-button.mdx
Labels: type: accepted/enhancement

#6425 Fix shared element transition on pop
  lib/ios/ContentTransitionCreator.h
  lib/ios/ContentTransitionCreator.m
  lib/ios/StackControllerDelegate.m
  lib/ios/StackTransitionDelegate.h
  lib/ios/StackTransitionDelegate.m
  lib/ios/TransitionDelegate.m
Labels: platform: iOS, type: accepted/bug

#6428 Fix option processors
  lib/src/Navigation.ts
  lib/src/commands/LayoutTreeCrawler.test.ts
  lib/src/commands/LayoutTreeCrawler.ts
  lib/src/commands/OptionsProcessor.test.ts
  lib/src/commands/OptionsProcessor.ts
  lib/src/interfaces/Processors.ts
  lib/src/processors/LayoutProcessor.test.ts
  lib/src/processors/LayoutProcessor.ts
Labels: type: accepted/bug

#6427 Change sideMenu.openGestureMode default to entireScreen
  lib/ios/RNNSideMenuPresenter.m
  playground/ios/NavigationTests/RNNSideMenuPresenterTest.m
  website/api/options-sideMenu.mdx
Labels: platform: iOS, type: accepted/enhancement

#6415 Fix playground docs
  website/docs/docs-playground-app.mdx
Labels: type: documentation

#6429 Document new apis
  website/docs/style-theme.mdx
Labels: type: documentation

#6423 Deprecate register component with redux
  lib/src/Navigation.ts
Labels: type: accepted/enhancement

#6424 Fix TouchablePreview regression
  lib/src/adapters/TouchablePreview.tsx
  playground/src/components/Button.tsx
Labels: platform: iOS, type: accepted/bug

#6419 Add primaryBackgroundStyle option to splitView
  lib/ios/RNNSplitViewControllerPresenter.m
  lib/ios/RNNSplitViewOptions.h
  lib/ios/RNNSplitViewOptions.m
  lib/ios/UISplitViewController+RNNOptions.h
  lib/ios/UISplitViewController+RNNOptions.m
  lib/src/commands/LayoutTreeParser.test.ts
  lib/src/interfaces/Options.ts
  website/api/options-splitView.mdx
Labels: platform: iOS, type: accepted/enhancement

#6434 Fix merging options
  lib/ios/NSObject+Utils.h
  lib/ios/NSObject+Utils.m
  lib/ios/RNNOptions.m
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
  playground/ios/NavigationTests/NSObjectUtilsTests.m
  playground/ios/playground.xcodeproj/project.pbxproj
Labels: platform: iOS, type: accepted/bug

#6437 Fix statusBar visibility through mergeOptions
  lib/ios/RNNBasePresenter.m
  playground/ios/NavigationTests/RNNBasePresenterTest.m
Labels: platform: iOS, type: accepted/bug

#6435 Fab id is mandatory
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/FabPresenter.java
  lib/src/interfaces/Options.ts
  playground/src/screens/ScrollViewScreen.tsx
Labels: type: accepted/enhancement

#6441 Resolve dismissModal promise with topmost parent componentId
  lib/ios/RNNBridgeManager.mm
  lib/ios/RNNBridgeModule.m
  lib/ios/RNNCommandsHandler.h
  lib/ios/RNNCommandsHandler.m
  lib/ios/RNNEventEmitter.h
  lib/ios/RNNEventEmitter.m
  lib/ios/RNNModalManager.h
  lib/ios/RNNModalManager.m
  lib/ios/RNNModalManagerEventHandler.h
  lib/ios/RNNModalManagerEventHandler.m
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
  playground/ios/NavigationTests/RNNCommandsHandlerTest.m
  playground/ios/NavigationTests/RNNModalManagerEventHandlerTest.m
  playground/ios/NavigationTests/RNNModalManagerTest.m
  playground/ios/playground.xcodeproj/project.pbxproj
Labels: platform: iOS, type: accepted/enhancement

#6444 Fixed bottomTabs syntax error
  website/api/layout-BottomTabs.mdx
Labels: type: documentation

#6446 Draw behind with constraints
  lib/ios/ElementTransitionsCreator.m
  lib/ios/RNNComponentPresenter.m
  lib/ios/RNNComponentViewController.h
  lib/ios/RNNComponentViewController.m
  lib/ios/RNNControllerFactory.m
  lib/ios/RNNReactView.h
  lib/ios/RNNSplitViewControllerPresenter.h
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
  lib/ios/SharedElementTransitionsCreator.m
  lib/ios/UIViewController+LayoutProtocol.h
  lib/ios/UIViewController+LayoutProtocol.m
  lib/ios/UIViewController+RNNOptions.h
  lib/ios/UIViewController+RNNOptions.m
  playground/ios/NavigationTests/RNNCommandsHandlerTest.m
  playground/ios/NavigationTests/RNNComponentPresenterTest.m
  playground/ios/NavigationTests/RNNStackControllerTest.m
  playground/ios/NavigationTests/RNNTestRootViewCreator.m
  playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m
  playground/ios/playground.xcodeproj/project.pbxproj
Labels: platform: iOS, type: accepted/enhancement

#6443 Set button text in dp
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonSpan.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TitleBarButtonControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TitleBarTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarButtonControllerTest.java
  lib/src/interfaces/Options.ts
  playground/src/screens/ButtonsScreen.tsx
  website/api/options-button.mdx
Labels: platform: Android, type: accepted/enhancement

#6448 Fix commands resolving
  e2e/Stack.test.js
  lib/ios/RNNBridgeModule.m
  lib/ios/RNNCommandsHandler.h
  lib/ios/RNNCommandsHandler.m
  lib/ios/RNNEventEmitter.h
  lib/ios/RNNEventEmitter.m
  lib/src/interfaces/Events.ts
  playground/ios/NavigationTests/RNNCommandsHandlerTest.m
  playground/ios/SnapshotTests/StackOptionsTest.m
  playground/src/screens/Screens.ts
  playground/src/screens/StackCommandsScreen.tsx
  playground/src/screens/StackScreen.tsx
  playground/src/screens/index.tsx
  playground/src/testIDs.ts
Labels: platform: iOS, type: accepted/bug
