Repository wix/react-native-navigation, pull requests merged in 2020-06, with the labels that each got.

#6256 [Docs] Modify functional components event listener example
  website/docs/docs-functional-components.mdx
Labels: type: documentation

#6273 Fix typo in React Context API documentation
  website/docs/third-party-react-context.mdx
Labels: type: documentation

#6276 Fix tabBar visibility
  e2e/BottomTabs.test.js
  lib/ios/RNNBasePresenter.m
  playground/src/screens/SecondBottomTabScreen.js
Labels: platform: iOS, type: accepted/bug

#6267 Handle errors in postlink scripts
  autolink/postlink/activityLinker.js
  autolink/postlink/appDelegateLinker.js
  autolink/postlink/applicationLinker.js
  autolink/postlink/gradleLinker.js
  autolink/postlink/podfileLinker.js
  autolink/postlink/postLinkAndroid.js
  autolink/postlink/postLinkIOS.js
  autolink/postlink/run.js
Labels: Infrastructure

#6269 Replace deprecated link process
  autolink/postlink/run.js
  package.json
  website/docs/docs-Installing.mdx
Labels: type: documentation

#6272 Add a new starter kit
  website/docs/docs-showcases.mdx
Labels: type: documentation

#6278 Fix duplicate SettingsScreen declaration in 'Basic Navigation' documentation
  website/docs/docs-basic-navigation.mdx
Labels: type: documentation

#6249 Add NavigationFunctionComponent interface
  lib/src/index.ts
  lib/src/interfaces/NavigationFunctionComponent.ts
Labels: type: accepted/enhancement

#6287 Ignoring yarn.lock and removed Podfile.lock from the project.
  .gitignore
  playground/ios/Podfile.lock
Labels: type: accepted/enhancement

#6280 Fix updateProps creating new props object
  lib/src/commands/Commands.ts
  lib/src/components/ComponentWrapper.tsx
Labels: type: accepted/enhancement

#6292 Skip creating navigator in case isFinishing in onCreate
  lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
Labels: platform: Android, type: accepted/bug

#6283 Implement bottomTabs.hideOnScroll
  lib/android/app/src/main/java/com/reactnativenavigation/parse/BottomTabsOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
  playground/src/screens/Screens.js
  playground/src/screens/ScrollViewScreen.js
  playground/src/screens/SecondBottomTabScreen.js
  playground/src/screens/index.js
  website/api/options-bottomTabs.mdx
Labels: platform: Android, type: accepted/enhancement

#6300 Fix Documentation link on Before you start page
  website/docs/docs-before-you-start.mdx
Labels: type: documentation

#6306 Run snapshot tests on iOS 13.3
  scripts/test-snapshot.js
Labels: Infrastructure

#6298 Restore bottomTabs visibility when needed
  e2e/BottomTabs.test.js
  lib/ios/BottomTabsBasePresenter.m
  lib/ios/RNNBasePresenter.m
  lib/ios/RNNBottomTabsController.h
  lib/ios/RNNBottomTabsController.m
  lib/ios/UITabBarController+RNNOptions.h
  lib/ios/UITabBarController+RNNOptions.m
  playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
  playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m
Labels: platform: iOS, type: accepted/bug

#6295 Fix return statement in the example code
  website/docs/docs-passing-data-to-components.mdx
Labels: type: documentation

#6291 Fix crash when disabledButtonColor is undefined
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ButtonSpan.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java
Labels: platform: Android, type: accepted/bug

#6294 TopBar title and subtitle font size is measured in dp instead of sp
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBar.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java
Labels: platform: Android, type: accepted/enhancement

#6311 Fix missing apostrophes
  website/docs/third-party-react-context.mdx
Labels: type: documentation

#6314 Fix updating currentTabIndex
  e2e/BottomTabs.test.js
  lib/ios/RNNBottomTabsController.m
  playground/src/screens/SecondBottomTabScreen.js
Labels: platform: iOS, type: accepted/bug

#6315 Fix broken imports
  lib/src/events/ComponentEventsObserver.ts
  lib/src/events/EventsRegistry.test.tsx
  lib/src/events/EventsRegistry.ts
Labels: type: accepted/bug

#6323 Upgrade React Native 0.62.2
  metro.config.js
  package.json
  playground/android/app/build.gradle
  playground/android/app/src/main/AndroidManifest.xml
  playground/android/gradle/wrapper/gradle-wrapper.properties
  playground/android/gradlew
  playground/ios/Podfile
  playground/ios/playground.xcodeproj/project.pbxproj
  scripts/test-unit.js
Labels: type: accepted/enhancement

#6324 Fix bottomTabs visibility when there is no stack
  e2e/SetRoot.test.js
  lib/ios/BottomTabsBasePresenter.m
  lib/ios/RNNBottomTabsController.h
  lib/ios/RNNBottomTabsController.m
  playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
  playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m
  playground/src/screens/SetRootScreen.js
  playground/src/testIDs.js
Labels: platform: iOS, type: accepted/bug

#6326 Fix registerBottomTabSelectedListener unselected value
  lib/ios/RNNBottomTabsController.m
  playground/ios/NavigationTests/BottomTabsControllerTest.m
  playground/ios/NavigationTests/RNNBottomTabsController+Helpers.m
Labels: platform: iOS, type: accepted/bug

#6317 Fix SearchBar false render
  lib/ios/RNNComponentPresenter.m
Labels: platform: iOS, type: accepted/bug

#6328 iOS installation documentation/autolink in parity with Playground app
  autolink/postlink/appDelegateLinker.js
  website/docs/docs-Installing.mdx
Labels: type: documentation

#6327 Fix bottomTabs long press event
  lib/ios/RNNBottomTabsController.h
  lib/ios/RNNBottomTabsController.m
  lib/ios/UITabBar+utils.h
  lib/ios/UITabBar+utils.m
  playground/ios/NavigationTests/BottomTabsControllerTest.m
  playground/src/app.js
Labels: platform: iOS, type: accepted/bug

#6334 Fix crash when currentTabIndex is defined
  lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java
Labels: platform: Android, type: accepted/bug

#6333 Parse icon only if it is defined
  lib/android/app/src/main/java/com/reactnativenavigation/parse/parsers/IconParser.java
Labels: platform: Android, type: accepted/bug

#6336 Set textual button color directly on button view
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ButtonPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ButtonPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ButtonSpan.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.kt
  lib/android/app/src/test/java/com/reactnativenavigation/fakes/IconResolverFake.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonPresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/ButtonSpanTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/utils/TitleBarHelper.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TitleBarTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/TopBarButtonControllerTest.java
Labels: platform: Android, type: accepted/bug

#6307 Fix wrong sideMenu dimensions after orientation change
  e2e/SideMenu.test.js
  lib/ios/RNNSideMenuChildVC.m
  playground/src/components/Root.js
  playground/src/screens/LayoutsScreen.js
  playground/src/screens/SideMenuLeftScreen.js
  playground/src/testIDs.js
Labels: platform: iOS, type: accepted/bug

#6347 Adding pre-commit hook and Enable Linter in documentation
  .gitignore
  .vscode/settings.json
  package.json
  website/docs/meta-contributing.mdx
Labels: type: accepted/enhancement, type: documentation
