Repository wix/react-native-navigation, pull requests merged in 2020-05, with the labels that each got.

#6170 Enforce PR labels
  .github/workflows/require-label.yml
Labels: type: accepted/enhancement

#6186 Use Overlay alert on iOS to address flakiness in CI
  playground/src/app.js
  playground/src/screens/LifecycleScreen.js
Labels: Infrastructure

#6188 Corrected typo in options-button.mdx
  website/api/options-button.mdx
Labels: type: documentation

#6187 Fix enforce label workflow
  .github/workflows/require-label.yml
Labels: Infrastructure

#6190 Fix typo in Issue template
  .github/ISSUE_TEMPLATE
Labels: type: documentation

#6199 Fix showing Modal from TopBar components in RN 62
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ViewUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ChildController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/NoOpYellowBoxDelegate.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/NoOpYellowBoxDelegate.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarReactViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/YellowBoxDelegate.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/YellowBoxDelegate.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/YellowBoxHelper.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/topbar/TopBarBackgroundViewController.java
  lib/android/app/src/reactNative62/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
  lib/android/app/src/reactNative62/java/com/reactnativenavigation/react/JsDevReloadHandlerFacade.java
  lib/android/app/src/reactNative62/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
  lib/android/app/src/reactNative62/java/com/reactnativenavigation/react/ReloadHandlerFacade.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestApplication.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/ViewControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/YellowBoxDelegateTest.java
Labels: platform: Android, type: accepted/bug

#6202 Fixed typo in docs/Screen Lifecycle page
  website/docs/docs-screen-lifecycle.mdx
Labels: type: documentation

#6212 Update api-overlay.mdx
  website/api/api-overlay.mdx
Labels: type: documentation

#6217 [Docs] Fix invalid links
  website/api/options-stack.mdx
  website/docs/docs-bottomTabs.mdx
  website/docs/docs-playground-app.mdx
  website/docs/style-animations.mdx
  website/docusaurus.config.js
Labels: type: documentation

#6218 Create github release note in CI
  .grenrc.js
  package.json
  scripts/release.js
Labels: Infrastructure

#6197 Unmount previous root before resolving setRoot promise
  e2e/StaticLifecycleEvents.test.js
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
  lib/ios/RNNCommandsHandler.m
  lib/ios/RNNComponentViewController.h
  lib/ios/RNNComponentViewController.m
  lib/ios/RNNReactView.h
  lib/ios/RNNReactView.m
  lib/ios/UIViewController+LayoutProtocol.h
  lib/ios/UIViewController+LayoutProtocol.m
  playground/src/screens/SetRootScreen.js
  playground/src/screens/StaticEventsScreen.js
  playground/src/screens/StaticLifecycleOverlay.js
  playground/src/screens/index.js
Labels: platform: Android, type: accepted/bug

#6219 Fix updating button options with mergeOptions
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/TitleBarButtonController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/StackPresenterTest.java
Labels: type: accepted/bug

#6220 Fix react-native-youtube support
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
Labels: type: accepted/bug

#6196 Update SideMenu enabled in parent
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuControllerTest.java
Labels: feature: SideMenu, platform: Android, type: accepted/bug

#6194 Mount all stack children
  lib/android/app/src/main/java/com/reactnativenavigation/react/ReactView.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/IdStack.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/ComponentLayout.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/IdStackTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.java
Labels: platform: Android, type: accepted/bug

#6221 Send screen popped event only for rnn components
  e2e/ExternalComponent.test.js
  lib/ios/RNNComponentViewController.m
  lib/ios/StackControllerDelegate.m
  lib/ios/UIViewController+LayoutProtocol.h
  lib/ios/UIViewController+LayoutProtocol.m
  playground/ios/NavigationTests/RNNExternalViewControllerTests.m
  playground/ios/playground.xcodeproj/project.pbxproj
  playground/ios/playground/AppDelegate.m
  playground/ios/playground/RNNCustomViewController.h
  playground/ios/playground/RNNCustomViewController.m
  playground/ios/playground/RNNNativeViewController.h
  playground/ios/playground/RNNNativeViewController.m
  playground/src/testIDs.js
Labels: platform: iOS, type: accepted/bug

#6225 Fix flickering FAB when changing bottom tabs
  lib/android/app/src/main/java/com/reactnativenavigation/presentation/FabPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerBuilder.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/FloatingActionButtonTest.java
Labels: platform: Android, type: accepted/bug

#6237 Fix "bellow" typos in docs
  website/docs/docs-Installing.mdx
  website/docs/third-party-mobx.mdx
Labels: type: documentation

#6241 Fixed syntax error in bottomTabs example
  website/docs/docs-bottomTabs.mdx
Labels: type: documentation

#6234 Overlay nested touchables
  e2e/Overlay.test.js
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/IReactView.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/ComponentLayout.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/touch/OverlayTouchDelegate.java
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleOverlay.java
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/TestComponentLayout.java
  lib/android/app/src/test/java/com/reactnativenavigation/views/TouchDelegateTest.java
  playground/src/screens/OptionsScreen.js
  playground/src/screens/OverlayScreen.js
  playground/src/screens/ScrollViewOverlay.js
  playground/src/screens/Toast.js
  playground/src/testIDs.js
Labels: platform: Android, type: accepted/bug

#6239 Fix component generator called multiple times
  lib/src/commands/Commands.ts
  lib/src/components/ComponentRegistry.test.tsx
  lib/src/components/ComponentRegistry.ts
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/components/Store.ts
Labels: type: accepted/bug

#6230 Fix bottomTabs visibility
  e2e/SetRoot.test.js
  lib/ios/BottomTabsBasePresenter.m
  lib/ios/BottomTabsTogetherAttacher.m
  lib/ios/RNNBottomTabsController.h
  lib/ios/RNNBottomTabsController.m
  lib/ios/RNNSplitViewController.m
  lib/ios/UIViewController+LayoutProtocol.h
  lib/ios/UIViewController+LayoutProtocol.m
  playground/ios/NavigationIOS12Tests/RNNBottomTabsPresenterTest.m
  playground/ios/NavigationIOS12Tests/RNNRootViewControllerTest.m
  playground/ios/NavigationTests/BottomTabsControllerTest.m
  playground/ios/NavigationTests/RNNBottomTabsAppearancePresenterTest.m
  playground/ios/NavigationTests/RNNBottomTabsController+Helpers.h
  playground/ios/NavigationTests/RNNBottomTabsController+Helpers.m
  playground/ios/NavigationTests/RNNCommandsHandlerTest.m
  playground/ios/NavigationTests/RNNControllerFactoryTest.m
  playground/ios/NavigationTests/RNNRootViewControllerTest.m
  playground/ios/NavigationTests/UIViewController+LayoutProtocolTest.m
  playground/src/screens/SetRootScreen.js
  playground/src/testIDs.js
Labels: platform: iOS, type: accepted/bug

#6203 Add missing typescript interfaces
  lib/src/events/ComponentEventsObserver.test.tsx
  lib/src/events/ComponentEventsObserver.ts
  lib/src/events/EventsRegistry.test.tsx
  lib/src/events/EventsRegistry.ts
  lib/src/index.ts
  lib/src/interfaces/NavigationComponent.ts
  lib/src/interfaces/NavigationComponentListener.ts
  lib/src/interfaces/NavigationComponentProps.ts
  playground/src/screens/index.js
  playground/src/screens/sharedElementTransition/CocktailsListScreen.tsx
  playground/src/screens/splitView/CocktailsListMasterScreen.tsx
  scripts/build.js
  scripts/start-windows.js
  scripts/watch.js
  tsconfig.build.json
  tsconfig.json
Labels: type: accepted/enhancement

#6248 Tag release versions only
  scripts/release.js
Labels: Infrastructure

#6250 Export NavigationComponentListener
  lib/src/index.ts
Labels: type: accepted/bug

#6246 fixes badgeColor in ios 13+
  lib/ios/UIViewController+RNNOptions.m
Labels: platform: iOS, type: accepted/bug

#6238 Fixes black screen when using animation in `dismissModal`
  lib/ios/ModalDismissTransitionDelegate.m
  lib/ios/ModalTransitionDelegate.m
  lib/ios/RNNAnimationsTransitionDelegate.m
  lib/ios/RNNPushAnimation.m
  lib/ios/TransitionDelegate.m
Labels: platform: iOS, type: accepted/bug

#6258 Export EventsRegistry
  lib/src/index.ts
Labels: type: accepted/enhancement
