Repository wix/react-native-navigation, pull requests merged in 2021-07, with the labels that each got.

#7140 Allow running jest tests by mocking react-native-navigation device layer
  e2e/ApplicationLifecycleTest.test.js
  e2e/BackButton.test.js
  e2e/BottomTabs.test.js
  e2e/Buttons.test.js
  e2e/ExternalComponent.test.js
  e2e/LazyRegsitration.test.js
  e2e/Modals.test.js
  e2e/Orientation.test.js
  e2e/Overlay.test.js
  e2e/SearchBar.test.js
  e2e/SideMenu.test.js
  e2e/SplitView.test.js
  e2e/Stack.test.js
  e2e/StaticLifecycleEvents.test.js
  e2e/init.js
  integration/redux/Redux.test.js
  integration/remx/remx.test.js
  jest-setup.js
  lib/src/Mock/Application.tsx
  lib/src/Mock/ComponentProps.tsx
  lib/src/Mock/Components/BottomTabs.tsx
  lib/src/Mock/Components/ComponentScreen.tsx
  lib/src/Mock/Components/LayoutComponent.tsx
  lib/src/Mock/Components/Modals.tsx
  lib/src/Mock/Components/NavigationButton.tsx
  lib/src/Mock/Components/Overlays.tsx
  lib/src/Mock/Components/Stack.tsx
  lib/src/Mock/Components/TopBar.tsx
  lib/src/Mock/Layouts/BottomTabsNode.ts
  lib/src/Mock/Layouts/ComponentNode.ts
  lib/src/Mock/Layouts/LayoutNodeFactory.ts
  lib/src/Mock/Layouts/Node.ts
  lib/src/Mock/Layouts/ParentNode.ts
  lib/src/Mock/Layouts/StackNode.ts
  lib/src/Mock/Stores/EventsStore.ts
  lib/src/Mock/Stores/LayoutStore.ts
  lib/src/Mock/connect.ts
  lib/src/Mock/constants.ts
  lib/src/Mock/index.ts
  lib/src/Mock/mocks/NativeCommandsSender.tsx
  lib/src/Mock/mocks/NativeEventsReceiver.ts
  lib/src/Navigation.ts
  lib/src/NavigationDelegate.ts
  lib/src/index.ts
  package.json
  playground/src/screens/LayoutsScreen.tsx
  wallaby.js
Labels: type: accepted/enhancement

#7172 update bottomTab option documentation
  website/docs/api/options-bottomTab.mdx
Labels: type: documentation

#7174 Move remx from devDependencies
  package.json
Labels: type: accepted/bug

#7177 Activity lifecycle send DidAppear & Disappear
  lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationModule.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/parent/ParentController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/navigator/NavigatorTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/parent/ParentControllerTest.java
Labels: platform: Android, type: accepted/bug

#7125 Compile jsx to plain js
  tsconfig.json
Labels: Infrastructure, type: accepted/bug

#7184 Warn when calling mergeOptions before component is mounted
  lib/src/commands/Commands.test.ts
  lib/src/commands/Commands.ts
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/components/Store.ts
Labels: type: accepted/enhancement

#7183 Run e2e on genymotion device
  e2e/AndroidUtils.js
  e2e/config.json
  e2e/global-setup.js
  e2e/global-teardown.js
  e2e/init.js
  package.json
  scripts/test-e2e.js
  scripts/test-snapshot.js
  scripts/test-unit.js
Labels: Infrastructure

#7186 Fix statusBar.blur option on iOS
  lib/ios/UIViewController+RNNOptions.m
  playground/ios/NavigationTests/RNNRootViewControllerTest.m
Labels: platform: iOS, type: accepted/bug

#7188 Added `constantsSync` to delegate, updated docs
  lib/src/NavigationDelegate.ts
  website/docs/docs/style-constants.mdx
Labels: type: accepted/bug, type: documentation

#7193 [Navigation mock] Should not pop when the stack have one child
  e2e/Stack.test.js
  lib/src/Mock/Stores/LayoutStore.ts
  playground/src/screens/StackScreen.tsx
Labels: Navigation mock, type: accepted/bug

#7194 Fix modals waitForRender
  lib/ios/RNNAnimationsOptions.h
  lib/ios/RNNAnimationsOptions.m
  lib/ios/RNNCommandsHandler.m
  lib/ios/TransitionOptions.h
  lib/ios/TransitionOptions.m
  lib/ios/ViewAnimationOptions.m
Labels: platform: iOS, type: accepted/bug

#7196 Fix persenting react-native modals from overlays
  lib/ios/RNNOverlayWindow.m
Labels: platform: iOS, type: accepted/bug

#7195 Render original top bar image when no color provided
  lib/ios/RNNUIBarButtonItem.m
Labels: platform: iOS, type: accepted/bug

#7169 setStackRoot crash & wrong ViewDidAppear event fix
  e2e/Stack.test.js
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
  playground/src/app.ts
  playground/src/commons/options/Options.ts
  playground/src/screens/StackScreen.tsx
  playground/src/testIDs.ts
Labels: platform: Android, type: accepted/bug

#7164 docs: Fix wrong API in example for custom button
  website/docs/docs/docs-stack.mdx
  website/docs/docs/stack-buttons.mdx
  website/versioned_docs/version-6.12.2/docs/docs-stack.mdx
  website/versioned_docs/version-6.12.2/docs/stack-buttons.mdx
  website/versioned_docs/version-7.11.2/docs/docs-stack.mdx
  website/versioned_docs/version-7.11.2/docs/stack-buttons.mdx
  website/versioned_docs/version-7.16.0/docs/docs-stack.mdx
  website/versioned_docs/version-7.16.0/docs/stack-buttons.mdx
  website/versioned_docs/version-7.7.0/docs/docs-stack.mdx
  website/versioned_docs/version-7.7.0/docs/stack-buttons.mdx
Labels: type: documentation

#7201 Disable button animations on iOS by default
  lib/ios/RNNComponentPresenter.m
  playground/ios/NavigationTests/RNNComponentPresenterTest.m
Labels: platform: iOS, type: accepted/bug

#7180 Use task lists in GitHub issue template
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: Infrastructure, skip-changelog

#7207 Update issues and features template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: Infrastructure, skip-changelog
