Repository wix/react-native-navigation, pull requests merged in 2022-04, with the labels that each got.

#7479 Resolve android crash on device rotate
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java
Labels: platform: Android, type: accepted/bug

#7500 Fix auto link on react-native 68+
  autolink/postlink/path.js
Labels: Infrastructure, type: accepted/bug

#7505 [Mocks] Postpone component lifecycle events to next loop
  .gitignore
  lib/Mock/Layouts/ComponentNode.ts
Labels: Infrastructure

#7507 Fix auto link on react-native 68+
  autolink/postlink/appDelegateLinker.js
Labels: Infrastructure
