Repository wix/react-native-navigation, pull requests merged in 2023-08, with the labels that each got.

#7758 Fix auto link for RN72 on Android
  autolink/postlink/applicationLinker.js
  autolink/postlink/gradleLinker.js
Labels: platform: Android, type: accepted/bug

#7760 Fix android build on RN72 and gradle 8
  lib/android/app/build.gradle
Labels: Infrastructure

#7744 New architecture support
  .gitignore
  Gemfile
  ReactNativeNavigation.podspec
  autolink/postlink/__snapshots__/appDelegateLinker.test.js.snap
  autolink/postlink/appDelegateLinker.js
  autolink/postlink/path.js
  babel.config.js
  e2e/Keyboard.test.js
  e2e/Utils.js
  lib/android/app/src/main/java/com/reactnativenavigation/react/ReactView.java
  lib/android/app/src/main/java/com/reactnativenavigation/react/modal/Events.kt
  lib/android/app/src/main/java/com/reactnativenavigation/utils/MotionEvent.kt
  lib/android/app/src/reactNative71/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
  lib/ios/RNNAppDelegate.h
  lib/ios/RNNAppDelegate.mm
  lib/ios/RNNComponentRootView.m
  lib/ios/RNNComponentViewController.m
  lib/ios/RNNOverlayWindow.m
  lib/ios/RNNReactButtonView.m
  lib/ios/RNNReactComponentRegistry.m
  lib/ios/RNNReactRootViewCreator.m
  lib/ios/RNNReactView.h
  lib/ios/RNNReactView.m
  lib/ios/RNNSideMenuChildVC.m
  lib/ios/RNNUIBarButtonItem.m
  lib/ios/ReactNativeNavigation.xcodeproj/project.pbxproj
  lib/src/adapters/NativeEventsReceiver.ts
  metro.config.js
  package.json
  playground/.gitignore
  playground/android/app/build.gradle
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
  playground/android/build.gradle
  playground/android/gradle.properties
  playground/android/settings.gradle
  playground/ios/.xcode.env
  playground/ios/Podfile
  playground/ios/playground.xcodeproj/project.pbxproj
  playground/ios/playground.xcodeproj/xcshareddata/xcschemes/playground.xcscheme
  playground/ios/playground.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  playground/ios/playground/AppDelegate.h
  playground/ios/playground/AppDelegate.mm
  scripts/test-e2e.js
Labels: platform: iOS, type: accepted/enhancement

#7761 Restore keyboard e2e tests
  e2e/Keyboard.test.js
Labels: Infrastructure

#7763 Update .nvmrc to use node 16
  .nvmrc
Labels: Infrastructure

#7764 Fix undefined props after calling setRoot with the same componentId
  lib/src/commands/LayoutTreeCrawler.test.ts
  lib/src/commands/LayoutTreeCrawler.ts
  lib/src/components/ComponentWrapper.tsx
  lib/src/components/Store.test.ts
  lib/src/components/Store.ts
  package.json
Labels: platform: iOS, type: accepted/bug

#7768 Fix white screen on push
  lib/ios/RNNComponentRootView.m
Labels: platform: iOS, type: accepted/bug

#7771 Fix build when fabric is enabled
  lib/ios/RNNComponentRootView.m
Labels: platform: iOS, type: accepted/bug

#7765 Update RNNSplashScreen.m
  lib/ios/RNNSplashScreen.m
Labels: platform: iOS, type: accepted/bug

#7775 Fix react-native.config.js
  react-native.config.js
Labels: Infrastructure
