Repository wix/react-native-navigation, pull requests merged in 2023-06, with the labels that each got.

#7728 Fix documentation Algolia search
  website/docusaurus.config.js
Labels: Infrastructure

#7730 Fix bottomTabs visibility on setRoot with second tab selected
  e2e/SetRoot.test.js
  lib/ios/RNNBottomTabsController.m
  playground/src/screens/SetRootScreen.tsx
  playground/src/testIDs.ts
Labels: platform: iOS, type: accepted/bug

#7731 [Mock] Fix initial bottomTabs selected index
  e2e/SetRoot.test.js
  jest.config.js
  lib/Mock/Layouts/BottomTabsNode.ts
Labels: Infrastructure

#7732 pass componentName prop to screens
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/interfaces/NavigationComponentProps.ts
Labels: type: accepted/enhancement

#7733 Fix linking on react-native 0.71
  autolink/fixtures/rn71/AppDelegate.mm.template
  autolink/fixtures/rn71/MainActivity.java.template
  autolink/postlink/__snapshots__/activityLinker.test.js.snap
  autolink/postlink/__snapshots__/appDelegateLinker.test.js.snap
  autolink/postlink/activityLinker.js
  autolink/postlink/activityLinker.test.js
  autolink/postlink/appDelegateLinker.js
  autolink/postlink/appDelegateLinker.test.js
  autolink/postlink/gradleLinker.js
Labels: Infrastructure

#7704 fix: measure overlay touch based on child dimensions
  lib/android/app/src/main/java/com/reactnativenavigation/utils/MotionEvent.kt
  lib/android/app/src/test/java/com/reactnativenavigation/utils/MotionEventTest.kt
Labels: platform: Android, type: accepted/bug

#7736 Fix truncated topBar component on Android
  lib/android/app/src/reactNative71/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
Labels: platform: Android, type: accepted/bug

#7739 Fix title component measurement on Android
  lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleAndButtonsContainer.kt
  lib/android/app/src/reactNative51/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative55/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative56/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative57/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative60/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative62/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative63/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative68/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
  lib/android/app/src/reactNative71/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt
Labels: platform: Android, type: accepted/bug

#7740 Revert "pass componentName prop to screens"
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/interfaces/NavigationComponentProps.ts
Labels: type: accepted/bug

#7737 Fix detox tests
  .npmrc
  e2e/BackButton.test.js
  e2e/config.json
  e2e/global-setup.js
  e2e/global-teardown.js
  e2e/init.js
  e2e/jest.config.js
  index.e2e.js
  package.json
  scripts/start.js
Labels: Infrastructure

#7714 RN Mock: push didAppear to next event loop
  jest-setup.js
  lib/Mock/Layouts/ComponentNode.ts
Labels: type: accepted/bug, Navigation mock
