Repository wix/react-native-navigation, pull requests merged in 2023-07, with the labels that each got.

#7745 Fix detox tests on Android
  e2e/SetRoot.test.js
  e2e/jest.config.js
  playground/src/screens/OverlayBanner.tsx
  scripts/test-e2e.js
Labels: Infrastructure

#7750 Use getConstants on main thread
  lib/ios/RNNBridgeModule.m
Labels: platform: iOS, type: accepted/bug

#7757 Pass componentName to NavigationProps
  lib/src/components/ComponentWrapper.test.tsx
  lib/src/components/ComponentWrapper.tsx
  lib/src/interfaces/NavigationComponent.ts
  lib/src/interfaces/NavigationComponentProps.ts
  lib/src/interfaces/NavigationFunctionComponent.ts
  playground/src/components/TopBarBackground.tsx
  playground/src/screens/Alert.tsx
  playground/src/screens/BackButtonScreen.tsx
  playground/src/screens/Button.tsx
  playground/src/screens/ContextScreen.tsx
  playground/src/screens/CustomTextButton.tsx
  playground/src/screens/CustomTopBar.tsx
  playground/src/screens/ExternalComponentScreen.tsx
  playground/src/screens/FirstBottomTabScreen.tsx
  playground/src/screens/FlatListScreen.tsx
  playground/src/screens/KeyboardScreen.tsx
  playground/src/screens/LayoutsScreen.tsx
  playground/src/screens/LazilyRegisteredScreen.tsx
  playground/src/screens/LazyTopBar.tsx
  playground/src/screens/LifecycleScreen.tsx
  playground/src/screens/ModalCommandsScreen.tsx
  playground/src/screens/NavigationScreen.tsx
  playground/src/screens/OptionsScreen.tsx
  playground/src/screens/OrientationDetectScreen.tsx
  playground/src/screens/OrientationScreen.tsx
  playground/src/screens/OverlayAlert.tsx
  playground/src/screens/OverlayBanner.tsx
  playground/src/screens/OverlayScreen.tsx
  playground/src/screens/PushedScreen.tsx
  playground/src/screens/RoundedButton.tsx
  playground/src/screens/ScrollViewScreen.tsx
  playground/src/screens/SearchBar.tsx
  playground/src/screens/SearchBarModal.tsx
  playground/src/screens/SearchScreen.tsx
  playground/src/screens/SecondBottomTabScreen.tsx
  playground/src/screens/SetRootScreen.tsx
  playground/src/screens/SideMenuCenterScreen.tsx
  playground/src/screens/StackCommandsScreen.tsx
  playground/src/screens/StackScreen.tsx
  playground/src/screens/StaticEventsScreen.tsx
  playground/src/screens/StaticLifecycleOverlay.tsx
  playground/src/screens/StatusBarFirstTab.tsx
  playground/src/screens/SystemUiOptions.tsx
  playground/src/screens/Toast.tsx
  playground/src/screens/TopTabOptionsScreen.tsx
  playground/src/screens/TopTabScreen.tsx
  playground/src/screens/complexlayouts/BottomTabSideMenuScreen.tsx
  playground/src/screens/complexlayouts/CustomDialogWithScroll.tsx
  playground/src/screens/sharedElementTransition/CocktailDetailsScreen.tsx
Labels: type: accepted/enhancement
