Repository wix/react-native-navigation, pull requests merged in 2024-02, with the labels that each got.

#7844 Support RN 73
  .buildkite/pipeline.yml
  .nvmrc
  ReactNativeNavigation.podspec
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
  lib/android/app/src/test/java/com/reactnativenavigation/EnvironmentTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestApplication.java
  lib/ios/RNNAppDelegate.mm
  lib/ios/RNNReactView.h
  lib/ios/RNNReactView.mm
  metro.config.js
  package.json
  playground/android/app/build.gradle
  playground/android/app/src/main/java/com/reactnativenavigation/playground/FragmentComponent.java
  playground/android/build.gradle
  playground/android/gradle/wrapper/gradle-wrapper.properties
  playground/ios/Podfile
  playground/ios/playground.xcodeproj/project.pbxproj
Labels: type: accepted/bug

#7848 Android: Fix ordering of top-bar left-hand button layout
  e2e/Buttons.test.js
  e2e/Utils.js
  e2e/assets/buttons_navbar.android.png
  e2e/assets/buttons_navbar.ios.png
  lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleAndButtonsContainer.kt
Labels: platform: Android, type: accepted/enhancement, feature: TopBar Buttons

#7850 Revert "build(playground): patch boost podspec on post-install."
  package.json
  scripts/postinstall.js
Labels: platform: iOS, type: accepted/bug

#7853 Rename Dictionary into RNNDictionary
  lib/ios/Dictionary.h
  lib/ios/Dictionary.m
  lib/ios/DictionaryParser.h
  lib/ios/DictionaryParser.m
  lib/ios/NullDictionary.h
  lib/ios/RNNBottomTabOptions.h
  lib/ios/RNNDictionary.h
  lib/ios/RNNDictionary.m
Labels: type: accepted/bug

#7851 fix: revert #7844 (React Native 73 support)
  .buildkite/pipeline.yml
  .nvmrc
  ReactNativeNavigation.podspec
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/button/ButtonPresenter.kt
  lib/android/app/src/test/java/com/reactnativenavigation/EnvironmentTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestApplication.java
  lib/ios/RNNAppDelegate.mm
  lib/ios/RNNReactView.h
  lib/ios/RNNReactView.m
  metro.config.js
  package.json
  playground/android/app/build.gradle
  playground/android/app/src/main/java/com/reactnativenavigation/playground/FragmentComponent.java
  playground/android/build.gradle
  playground/android/gradle/wrapper/gradle-wrapper.properties
  playground/ios/Podfile
  playground/ios/playground.xcodeproj/project.pbxproj
  playground/ios/scripts/pre-install.js
Labels: type: accepted/bug

#7856 Bump detox@20.18.3
  package.json
Labels: Infrastructure, type: accepted/enhancement
