Repository wix/react-native-navigation, pull requests merged in 2025-04, with the labels that each got.

#7991 Fix SDK35 Bottom-tab positioning
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
Labels: platform: Android, type: accepted/bug

#7992 Fix SDK35 Bottom-tab positioning
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
Labels: platform: Android, type: accepted/bug

#7999 Android Turbo Modules
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationPackage.kt
  lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationTurboModule.kt
  lib/android/build.gradle
  lib/ios/Constants.mm
  lib/src/adapters/NativeCommandsSender.ts
  lib/src/adapters/NativeRNNTurboModule.ts
  lib/src/commands/Commands.test.ts
  package-lock.json
  package.json
  playground/android/app/build.gradle
Labels: Infrastructure

#8005 Feat/rn 76 to 77 upgrade
  .eslintrc.js
  autolink/postlink/__snapshots__/appDelegateLinker.test.js.snap
  index.e2e.js
  lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationPackage.kt
  lib/ios/RNNAppDelegate.mm
  lib/src/adapters/NativeRNNTurboEventEmitter.ts
  package-lock.json
  package.json
  playground/index.js
  playground/ios/playground/AppDelegate.mm
Labels: Infrastructure

#8006 fix(Android): Turbo module generation
  lib/android/app/build.gradle
  react-native.config.js
Labels: type: accepted/bug
