Repository wix/react-native-navigation, pull requests merged in 2025-08, with the labels that each got.

#8041 feat(Android): #8011 Convert disabled Android Unit Tests to Instrumentation Tests
  lib/android/app/build.gradle
  lib/android/app/src/androidTest/AndroidManifest.xml
  lib/android/app/src/androidTest/java/com/reactnativenavigation/BaseAndroidTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/TestActivity.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/TestApplication.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/TestUtils.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/fakes/IconResolverFake.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/BackDrawable.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/ImageLoaderMock.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/SimpleViewController.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/TitleBarButtonCreatorMock.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/TitleBarReactViewCreatorMock.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/TopBarBackgroundViewCreatorMock.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/mocks/TypefaceLoaderMock.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/utils/ButtonPresenterTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/AfterInitialTabTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/AttachModeTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/OnSwitchToTabTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/TogetherTest.kt
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/child/ChildControllerTest.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/child/ChildControllersRegistryTest.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/viewcontrollers/parent/ParentControllerTest.java
  lib/android/app/src/androidTest/java/com/reactnativenavigation/views/TitleSubTitleLayoutTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/presentation/PresenterTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/AfterInitialTabTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/AttachModeTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/OnSwitchToTabTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/attacher/modes/TogetherTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllerTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/child/ChildControllersRegistryTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/views/TitleAndButtonsContainerTest.kt
  package-lock.json
  playground/android/gradle.properties
  scripts/test-unit.js
Labels: type: accepted/enhancement

#8089 Fix Property setImmediate doesn't exist issue
  lib/ios/RNNAppDelegate.mm
Labels: type: accepted/bug

#8090 Fix keyboard-awareness bug (#8087)
  e2e/AndroidUtils.js
  e2e/Keyboard.test.js
  e2e/Utils.js
  e2e/drivers/androidKeyboard.js
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  playground/src/screens/KeyboardScreen.tsx
  playground/src/testIDs.ts
Labels: type: accepted/bug

#8098 Fix crash coming from top-bar color animation
  lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutFactory.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt
Labels: type: accepted/bug

#8099 Fix crash due to java2kotlin refactor (#8095)
  lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
Labels: type: accepted/bug

#8103 Fix crash coming from top-bar color animation (#8098)
  lib/android/app/src/androidTest/java/com/reactnativenavigation/TestUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutFactory.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
  lib/android/app/src/test/java/com/reactnativenavigation/TestUtils.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/OptionsApplyingTest.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackControllerTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenterTest.kt
Labels: platform: Android, type: accepted/bug
