Repository wix/react-native-navigation, pull requests merged in 2025-03, with the labels that each got.

#7975 Apply color animations on tab-switching (Android-only)
  lib/android/app/src/main/java/com/reactnativenavigation/FeatureToggles.kt
  lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ColorUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarController.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/TopBarController.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/StatusBarColorAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerVisibilityInfo.kt
  lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/TitleBarReactViewCreatorMock.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
  playground/src/screens/NavigationScreen.tsx
Labels: type: accepted/enhancement

#7977 Apply color animations on tab-switching (Android-only) (Merge from #7975)
  lib/android/app/src/main/java/com/reactnativenavigation/FeatureToggles.kt
  lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ColorUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/utils/SystemUiUtils.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarController.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/statusbar/StatusBarPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/topbar/TopBarController.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/statusbar/StatusBarPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/Presenter.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/StatusBarColorAnimator.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/viewcontroller/ViewControllerVisibilityInfo.kt
  lib/android/app/src/test/java/com/reactnativenavigation/BaseTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/TitleBarReactViewCreatorMock.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/stack/TopBarControllerTest.kt
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
  playground/src/screens/NavigationScreen.tsx
Labels: platform: Android, type: accepted/enhancement

#7985 Update package-lock.json
  package-lock.json
Labels: type: accepted/enhancement

#7984 Support drawer menus opening as overlay instead of pushing content in ios
  lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.h
  lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
  lib/ios/RNNSideMenuPresenter.m
  lib/ios/RNNSideMenuSideOptions.h
  lib/ios/RNNSideMenuSideOptions.m
  lib/src/interfaces/Options.ts
  package-lock.json
  playground/ios/NavigationTests/RNNSideMenuPresenterTest.m
  playground/src/screens/SetRootScreen.tsx
  playground/src/testIDs.ts
Labels: platform: iOS, type: accepted/enhancement

#7987 Fix npm registry (lock on public)
  .npmrc
  package-lock.json
Labels: Infrastructure, type: accepted/enhancement

#7988 Fix npm registry (lock on public)
  .npmrc
  package-lock.json
Labels: Infrastructure, type: accepted/enhancement

#7989 Revert #7984 (sidemenu as overlay) temporarily
  lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.h
  lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
  lib/ios/RNNSideMenuPresenter.m
  lib/ios/RNNSideMenuSideOptions.h
  lib/ios/RNNSideMenuSideOptions.m
  lib/src/interfaces/Options.ts
  playground/ios/NavigationTests/RNNSideMenuPresenterTest.m
  playground/src/screens/SetRootScreen.tsx
  playground/src/testIDs.ts
Labels: type: accepted/enhancement, feature: SideMenu
