Repository wix/react-native-navigation, pull requests merged in 2025-06, with the labels that each got.

#8034 bugfix(iOS): Fixed broken turbo modules interop
  lib/ios/RNNAppDelegate.mm
Labels: type: accepted/bug

#8039 Patch-fix some recent side-menu overlay mode changes
  e2e/SideMenu.test.js
  e2e/assets/side_menu.undefined.png
  playground/src/screens/SideMenuCenterScreen.tsx
  playground/src/testIDs.ts
Labels: platform: iOS, type: accepted/enhancement, feature: SideMenu

#8033 (RN77-NA) Bug(iOS): React Native Reload is not working #8021
  lib/ios/RNNBridgeEventEmitter.mm
  lib/ios/RNNEventEmitter.h
  lib/ios/RNNEventEmitter.mm
  lib/ios/RNNReactButtonView.mm
  lib/ios/RNNReactView.h
  lib/ios/RNNReactView.mm
  lib/ios/StackControllerDelegate.h
  lib/ios/StackControllerDelegate.mm
  lib/ios/TurboModules/RNNTurboEventEmitter.h
  lib/ios/TurboModules/RNNTurboEventEmitter.mm
  lib/ios/TurboModules/RNNTurboManager.mm
  lib/ios/UINavigationController+RNNCommands.mm
Labels: platform: iOS, type: accepted/bug

#8043 feat(iOS): RN-77 Swift support (#8037)
  ReactNativeNavigation.podspec
  autolink/fixtures/rn68/AppDelegate.mm.template
  autolink/fixtures/rn69/AppDelegate.mm.template
  autolink/fixtures/rn77/AppDelegate.mm.template
  autolink/fixtures/rn77/AppDelegate.swift.template
  autolink/postlink/__snapshots__/appDelegateLinker.test.js.snap
  autolink/postlink/appDelegateLinker.js
  autolink/postlink/appDelegateLinker.test.js
  autolink/postlink/path.js
Labels: platform: iOS, type: accepted/enhancement

#8042 Improve Documentation for RNN Installation
  lib/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java
  playground/android/app/build.gradle
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainActivity.java
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainActivity.kt
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.kt
  playground/android/build.gradle
  website/docs/docs/docs-Installing.mdx
Labels: type: accepted/enhancement

#8047 Patch improvements into revised, v8.x.x install guide
  website/docs/docs/docs-Installing.mdx
Labels: type: documentation, type: accepted/enhancement
