Repository wix/react-native-navigation, pull requests merged in 2025-07, with the labels that each got.

#8056 Fix swift delegate detection
  ReactNativeNavigation.podspec
Labels: platform: iOS, type: accepted/bug

#8070 RNDatePicker not registering - including any 3rd party component - #8069
  lib/ios/RNNAppDelegate.mm
Labels: type: accepted/bug

#8064 Introduce options to make a floating bottom-tabs (Android)
  e2e/BottomTabs.test.js
  e2e/assets/bottom_tabs.stylized-root.png
  e2e/assets/bottom_tabs.stylized.png
  lib/android/app/build.gradle
  lib/android/app/src/main/java/com/reactnativenavigation/FeatureToggles.kt
  lib/android/app/src/main/java/com/reactnativenavigation/options/BottomTabsOptions.java
  lib/android/app/src/main/java/com/reactnativenavigation/options/LayoutDirection.java
  lib/android/app/src/main/java/com/reactnativenavigation/options/params/BottomTabsLayoutStyle.kt
  lib/android/app/src/main/java/com/reactnativenavigation/utils/ColorUtils.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsPresenter.kt
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabs.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabsContainer.kt
  lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/BottomTabsLayout.java
  lib/android/app/src/main/java/com/reactnativenavigation/views/bottomtabs/ShadowLayout.kt
  lib/android/app/src/test/java/com/reactnativenavigation/mocks/SimpleViewController.java
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsControllerTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsPresenterTest.kt
  lib/android/app/src/test/java/com/reactnativenavigation/views/bottomtabs/BottomTabsContainerTest.kt
  lib/src/interfaces/Options.ts
  playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java
  playground/src/components/Root.tsx
  playground/src/screens/BottomTabsLayoutStructure.ts
  playground/src/screens/FirstBottomTabScreen.tsx
  playground/src/screens/LayoutsScreen.tsx
  playground/src/testIDs.ts
  website/docs/api/options-bottomTabs.mdx
  website/docs/docs/docs-bottomTabs.mdx
Labels: type: accepted/enhancement

#8076 Bugfix/8053 apply on7xx
  lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java
Labels: platform: Android, type: accepted/bug
